#!/bin/bash

if [ $1 ] ; then
	line=$1
else
	echo 'Enter the name of the round: '
	read line
fi

mkdir $line
cp link test sample.cpp $line
cp .getInput\.cpp .reset .runTests $line

cd $line
touch input
echo $line > .roundName 

g++ -std=c++0x -w -o .getInput .getInput.cpp

for var in {A..E}; do
	cp sample.cpp $var.cpp
done

echo "OK"

